---

- include: create_swap_file.yml
  when: create_swap_file
  tags: swap

- name: Ensure bash, OpenSSL, and libssl are the latest versions
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
  tags: packages

- name: Install base packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - build-essential
    - acl
    - ntp
    - htop
    - git
    - libpq-dev
    - python-dev
    - python-pip
    - python-pycurl
    - ipython
    - supervisor
  tags: packages

- name: Upgrade pip
  pip: name=pip state=latest
  tags: packages

- name: Add repository for Python 3.5 to the sources list
  apt_repository: repo='ppa:fkrull/deadsnakes'
                  update_cache={{ update_apt_cache }}
                  state=present

- name: Install Python 3.5 and related packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=present
  with_items:
    - python3.5
    - python3.5-dev
    - python3-pip
    - ipython3
    - libtiff5-dev
    - libjpeg8-dev
    - zlib1g-dev
    - libfreetype6-dev
    - liblcms2-dev
    - libwebp-dev
    - tcl8.6-dev
    - tk8.6-dev
    - python-tk
   # Beyond ipython3 is needed for Pillow https://stackoverflow.com/questions/34631806/fail-during-installation-of-pillow-python-module-in-linux#34631976 
  tags: packages
